import React from 'react';
import "./Covid19.css"

const Covid19 = () => {
    return (
        <div >
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
             <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
            <h3>Hey Post</h3>
        </div>
    );
};

export default Covid19;